project:
  output-dir: docs

execute:
  freeze: auto
    
format: 
    revealjs:
        css: assets/styles.css
        bibliography: assets/references.bib
        csl: assets/nature.csl
        date-format: long
        slide-number: true
        preview-links: auto
        html-math-method: mathjax

