project:
  output-dir: docs

execute:
  freeze: auto
    
format: 
    revealjs:
        slide-number: true
        preview-links: auto
        css: assets/styles.css
        html-math-method: mathjax

